import { SkillsType } from '../types/SkillType';

const skillsData: SkillsType = [
  {
    url: '/resume/js.png',
    altText: 'JavaScript img',
    name: 'JavaScript',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/resume/ts.png',
    altText: 'TypeScript img',
    name: 'Typescript',
    percentage: 20,
    category: 'language',
  },
  {
    url: '/resume/html.svg',
    altText: 'HTML img',
    name: 'HTML',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/resume/css.svg',
    altText: 'CSS img',
    name: 'CSS',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/resume/csharp.svg',
    altText: 'C# img',
    name: 'C#',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/resume/vb.svg',
    altText: 'VB.NET img',
    name: 'VB.NET',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/resume/postgresql.svg',
    altText: 'SQL img',
    name: 'PostgreSQL',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/resume/vue.svg',
    altText: 'Vue.js img',
    name: 'Vue.js',
    percentage: 80,
    category: 'framework',
  },
  {
    url: '/resume/react.svg',
    altText: 'React img',
    name: 'React',
    percentage: 20,
    category: 'framework',
  },
  {
    url: '/resume/jquery.svg',
    altText: 'jQuery img',
    name: 'jQuery',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/resume/nextjs.svg',
    altText: 'Next.js img',
    name: 'Next.js ',
    percentage: 20,
    category: 'framework',
  },
  {
    url: '/resume/figma.svg',
    altText: 'Figma img',
    name: 'Figma',
    percentage: 80,
    category: 'tool',
  },
  {
    url: '/resume/git.svg',
    altText: 'Git img',
    name: 'Git',
    percentage: 80,
    category: 'tool',
  },
  {
    url: '/resume/docker.svg',
    altText: 'Docker img',
    name: 'Docker',
    percentage: 40,
    category: 'tool',
  },
  {
    url: '/resume/aws.svg',
    altText: 'AWS img',
    name: 'AWS',
    percentage: 20,
    category: 'tool',
  },
];
export default skillsData;
