import { SkillsType } from '../types/SkillType';

export const skillsData: SkillsType = [
  {
    url: '/js.png',
    altText: 'JavaScript img',
    name: 'JavaScript',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/ts.png',
    altText: 'TypeScript img',
    name: 'Typescript',
    percentage: 40,
    category: 'language',
  },
  {
    url: '/html.svg',
    altText: 'HTML img',
    name: 'HTML',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/css.svg',
    altText: 'CSS img',
    name: 'CSS',
    percentage: 80,
    category: 'language',
  },
  {
    url: '/csharp.svg',
    altText: 'C# img',
    name: 'C#',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/vb.svg',
    altText: 'VB.NET img',
    name: 'VB.NET',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/postgresql.svg',
    altText: 'SQL img',
    name: 'PostgreSQL',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/vue.svg',
    altText: 'Vue.js img',
    name: 'Vue.js',
    percentage: 80,
    category: 'framework',
  },
  {
    url: '/react.svg',
    altText: 'React img',
    name: 'React',
    percentage: 40,
    category: 'framework',
  },
  {
    url: '/jquery.svg',
    altText: 'jQuery img',
    name: 'jQuery',
    percentage: 60,
    category: 'language',
  },
  {
    url: '/nextjs.svg',
    altText: 'Next.js img',
    name: 'Next.js ',
    percentage: 20,
    category: 'framework',
  },
  {
    url: '/figma.svg',
    altText: 'Figma img',
    name: 'Figma',
    percentage: 80,
    category: 'tool',
  },
  {
    url: '/git.svg',
    altText: 'Git img',
    name: 'Git',
    percentage: 80,
    category: 'tool',
  },
  {
    url: '/docker.svg',
    altText: 'Docker img',
    name: 'Docker',
    percentage: 40,
    category: 'tool',
  },
  {
    url: '/aws.svg',
    altText: 'AWS img',
    name: 'AWS',
    percentage: 10,
    category: 'tool',
  },
];
